### ISSUE TITLE
Couldn't register URI scheme due to: The type initializer for 'Microsoft.Win32.Registry' threw an exception.

### ISSUE THREAD

**Issue by Phara0h** [cswendrowski/FoundryVTT-Discord-Rich-Presence#15]
Getting this error when trying to run it on a mac. chmod +x and chmod 777 the file and even ran it as root to try to see if that fixed it.

**Comment by cswendrowski** [comment]
Howdy!

You're my first Mac user, so we will have to do a bit of back and forth
testing since I don't own a mac.

It's probable that the Registry api that I am using doesn't work on a Mac.
I'll look into options

I'm off on vacation until the 10th, so I'll look at this when I get back.
Cheers!

On Feb 28, 2020 at 23:01, Jt Whissel <notifications@github.com> wrote:

Getting this error when trying to run it on a mac. chmod +x and chmod 777
the file and even ran it as root to try to see if that fixed it.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/cswendrowski/FoundryVTT-Discord-Rich-Presence/issues/15?email_source=notifications&email_token=ADXKKILKEOOV65BGOC7FNLDRFCLCHA5CNFSM4K6M5GU2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4IRJ7B6A>,
or unsubscribe

**Comment by Phara0h** [comment]
No problem willing to help any way I can :)

**Comment by timothy-boyd** [comment]
I'm in linux trying to get Foundry going and it is throwing a similar error here is a screen shot
![Screenshot](https://user-images.githubusercontent.com/45023833/79812248-fc752200-833d-11ea-96ee-5cc4f5838451.png)

**Comment by Javiondox** [comment]
The same error still happens on the current version of Manjaro (Linux).
![Screenshot_20200613_133501](https://user-images.githubusercontent.com/57767414/84567707-b2774e00-ad7a-11ea-992d-e8ba805dcd1d.png)

**Comment by cswendrowski** [comment]
Apologies for the very long delay, but this should now be resolved

**Comment by BoltsJ** [comment]
I'm still getting this problem on Pop_OS 20.10. It seems that `libdiscord_game_sdk.so` is missing from the distribution.

Update: Downloading the so from the repo and dropping it in the folder with the companion ap resolves it. https://github.com/cswendrowski/FoundryVTT-Discord-Rich-Presence/blob/master/LocalApi/DiscordSdk/discord_game_sdk.so
